meta_product_name: "Vizi"
meta_title: "Vizi - Experience new sports thanks to your neighbours"
meta_description: "Vizi is a collaborative platform where you can rent or sell your sports equipments, for your neighbours to enjoy them!"
meta_image: "cover.jpg" # should exist in `app/assets/images/`

